version: "3.8"
services:
  tuneuptechnology-docs:
    labels:
      - "traefik.http.routers.tuneuptechnology-docs.rule=Host(`tuneuptechnology-docs.localhost`)"
    volumes:
      - ./src:/var/www/html/public
