version: "3.8"
services:
  tuneuptechnology-docs:
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.http.routers.tuneuptechnology-docs.rule=Host(`docs.tuneuptechnology.com`) || Host(`www.docs.tuneuptechnology.com`)"
      - "traefik.http.routers.tuneuptechnology-docs.tls=true"
      - "traefik.http.routers.tuneuptechnology-docs.tls.certresolver=letsencrypt"
