version: "3.8"
services:
  tuneuptechnology-docs:
    build: .
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.port=80

networks:
  traefik:
    name: traefik
