version: "3.8"
services:
  tuneuptechnology-docs:
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.frontend.rule=Host:docs.tuneuptechnology.com,www.docs.tuneuptechnology.com
