name: build

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Traefik
        run: docker network create traefik
      - name: Setup Docker container
        run: |
          docker compose up -d
          docker ps | grep -q tuneuptechnology-docs-tuneuptechnology-docs-1
  deploy:
    needs: ["docker"]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Harvey
        if: github.ref == 'refs/heads/main'
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: "json-extended"
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "pipeline": "deploy", "prod_compose": true, "healthcheck": ["tuneuptechnology-docs-tuneuptechnology-docs-1", "tuneuptechnology-docs-tuneuptechnology-docs-2"] }'
